service: aftp-demo

provider: 
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
package:
  include: 
    - index.js
  exclude:
    - .idea/**
    - .git/**
    - .project
    - config.json
    - package.json
    - readme.md
    - setenv-*.sh
    - testaftp.jar
    - README.md
    - build_all.sh
    - remove_all.sh
    - package-lock.json
  excludeDevDependencies: true
functions:
  aftp-demo:
    name: aftp-demo
    description: Automation for the People
    handler: index.aftp
    memorySize: 128
    runtime: nodejs8.10
    timeout: 30
    role: LambdaRole
    tags:
      Owner: ${env:OWNER_TAG}
    events:
      - http:
          path: /message
          method: get
resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /lambda/
        RoleName: aftp-demo-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - Effect: Allow
              Principal: 
                Service: 
                  - lambda.amazonaws.com
              Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AWSLambdaExecute"
